// Feature data (Consider moving to a constants file if used elsewhere)
const features = [
  {
    icon: '🎯',
    title: 'Personalized Content',
    description: "Stories featuring your child's name, interests, and favorite characters.",
    color: 'bg-[#fa6565]/10'
  },
  {
    icon: '🎨',
    title: 'AI-Powered Creativity',
    description: 'Unique stories generated by advanced AI, ensuring endless variety.',
    color: 'bg-[#f2c955]/10'
  },
  {
    icon: '⚡',
    title: 'Instant Delivery',
    description: 'Receive your story via email within minutes, ready to play.',
    color: 'bg-[#fa6565]/10'
  }
];

export default function FeaturesSection() {
  return (
    <div id="features" className="py-12 sm:py-20 bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-8 sm:mb-16">
          <h2 className="text-2xl sm:text-3xl font-bold text-[#171c3f]">
            Why Parents Love Our Stories
          </h2>
          <p className="mt-4 text-lg sm:text-xl text-[#171c3f]/80 max-w-3xl mx-auto leading-relaxed">
            We combine cutting-edge AI with child psychology to create engaging, educational, and magical stories.
          </p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 sm:gap-8">
          {features.map((feature, index) => (
            <div key={index} className="bg-white rounded-2xl p-8 shadow-lg hover:shadow-xl transition-all duration-300 border border-[#171c3f]/5">
              <div className={`w-12 h-12 rounded-xl ${feature.color} flex items-center justify-center mb-4`}>
                <span className="text-2xl">{feature.icon}</span>
              </div>
              <h3 className="text-xl font-semibold text-[#171c3f] mb-2">{feature.title}</h3>
              <p className="text-[#171c3f]/80 leading-relaxed">{feature.description}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
} 